---
- name: Install dependencies on Debian Image
  hosts: all
  become: yes  
  vars:   
    packages:
     - apache2
   
  tasks:
    - name: Update apt packages
      become: true
      apt:
        upgrade: no
        update_cache: yes

    - name: Install apache2
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes

    - name: Start and enable apache2 service
      systemd:
        name: apache2
        state: started
        enabled: yes


